" No Vi compatability
set nocompatible

" Unicode support
set encoding=utf-8

" Special characters
set list
set listchars=tab:»·,trail:·,extends:…

" Line numbers and cursor position
set number
set ruler

" Text formatting
set autoindent
set noexpandtab
set shiftwidth=4
set tabstop=4
set cinoptions=:0,g0,(1s

" Rust
let g:rust_recommended_style=0

" Syntax hilighting
set t_Co=256
syntax on
set background=dark
colorscheme inkpot

filetype plugin indent on

" C/C++ specifics
autocmd FileType c,cpp source ~/etc/vim/c

source ~/etc/vim/keys
