" No Vi compatability
set nocompatible

" Unicode support
set encoding=utf-8

" Special characters
set list
set listchars=tab:»·,trail:·,extends:…

" Line numbers and cursor position
set number
set ruler

" Text formatting
set autoindent
set noexpandtab
set shiftwidth=4
set tabstop=4
set cinoptions=:0,g0,(1s

" Syntax hilighting
set t_Co=256
syntax on
colorscheme inkpot

filetype plugin indent on

" C/C++ specifics
function s:C()
	syn keyword cConstant nil
	syn keyword cOperator constant expect likely unlikely offsetof
	syn keyword cStorageClass nothrow pure perfect
endfunction

autocmd FileType c,cpp call s:C()

source ~/etc/vim/keys
